bot:
  map: east_rocky_mountain_6
buff_skill:
  keys:
  - ins
directional_aoe:
  range_x: 400
directional_attack:
  range_x: 400
  range_y: 50
game_window:
  auto_resize: false
  capture_profile: potplayer
  preserve_native_resolution: true
  title: "TV/CAM/\u8BBE\u5907 - PotPlayer"
health_monitor:
  add_hp_percent: 0
  add_mp_percent: 0
  enable: false
key:
  directional_attack: control
  jump: alt
nametag:
  medal:
    enable: true
  name: liu_muning
  overhead_marker:
    enable: true
  pet:
    enable: true
  template_reference_size:
  - 2013
  - 3579
power_knockback:
  trigger_distance_x: 20
