bot:
  map: wisdom_forest
game_window:
  capture_profile: potplayer
  title: "TV/CAM/\u8BBE\u5907 - PotPlayer"
health_monitor:
  add_hp_percent: 0
  add_mp_percent: 0
  enable: false
key:
  aoe_skill: shift
  directional_attack: control
  jump: alt
nametag:
  enable: true
  medal:
    enable: true
  name: liu_muning
  pet:
    enable: true
