bot:
  map: forest_floor
buff_skill:
  cooldown:
  - 600
  - 60
  - 60
  keys:
  - ins
  - t
  - y
directional_aoe:
  range_x: 400
directional_attack:
  cooldown: 0.65
  range_x: 400
  range_y: 60
game_window:
  auto_resize: false
  preserve_native_resolution: true
health_monitor:
  add_hp_percent: 0
  add_mp_percent: 0
  enable: false
key:
  directional_attack: a
  jump: alt
monster_detect:
  confidence: 0.6
  min_box_height: 40
  min_box_width: 40
nametag:
  appearance:
    enable: false
  name: liu_muning
  template_reference_size:
  - 2160
  - 3840
power_knockback:
  trigger_distance_x: 40
